### ISSUE TITLE
Recommendations should focus on "minimal" ROAs

### ISSUE THREAD

**Issue by benmaddison** [goldbe/draft-rpki-maxlength#3]
The recommendations section as written seems to imply that `maxLength` is undesirable in-and-of-itself:

> Operators SHOULD avoid using the maxLength attribute in their ROAs except in some special cases. One such exception may be when all more specific prefixes permitted by the maxLength are actually announced by the AS in the ROA. Another exception for use of maxLength is when (a) the maxLength is substantially larger compared to the specified prefix length in the ROA, and (b) a large number of more specific prefixes in that range is announced by the AS in the ROA. This case should occur rarely in practice (if at all). Operator discretion is necessary in this case.
> 
> Operators SHOULD use "minimal ROAs" whenever possible.
> A minimal ROA contains only those IP prefixes that are actually originated by an AS in BGP, and no other IP prefixes.

I believe that what we mean to say is, "operators SHOULD ensure that ROAs are minimal, and that generally speaking, the inclusion of `maxLength` greater than `prefix` length will result in a ROA that is not minimal"?

Happy to attempt wording if we all agree?

**Comment by ksriram25** [comment]
I think what is in the draft is in sync with how you paraphrased it. Please go ahead and reword as you feel best.
