### ISSUE TITLE
"Measurements of Today's RPKI" section hard to parse

### ISSUE THREAD

**Issue by benmaddison** [goldbe/draft-rpki-maxlength#4]
I struggle to parse the sentence:

> Network measurements from June 1, 2017 show that 12% of the IP prefixes authorized in ROAs have a maxLength longer than their prefix length.

Do we mean that 12% of the prefixes announced in the DFZ that are covered by a ROA have length < `maxLength` of the ROA that covers them?
If that is the case, why are only 84% of those vulnerable to sub-prefix hijack? Is it because there is also a route for all of the longest prefixes authorised in the same ROA?

I'm sure I could just go and read the ref, but *time*!

If my reading is correct, then I think it can be made clearer, as I needed a couple of scans to get there.

**Comment by ksriram25** [comment]
Ben: I have the same understanding as you. Yossi can comment. I would say, you please go ahead to add wording to make it clear.
