### ISSUE TITLE
DDoS Section Issues

### ISSUE THREAD

**Issue by benmaddison** [goldbe/draft-rpki-maxlength#5]
I think there are a few issues with the section dealing with the difficulties with DDoS mitigation:
- The issues raised apply to any scenario where a longer prefix may need to be announced at short notice. It should be clear that DDoS mitigation is just one (particularly neat) example
- The description seems to suggest that the problem arrises because another AS originates the more-specific. In fact, the same issues exist even if the more-specific originates at the same AS and the mitigation provider announces transit for it (i.e. a resulting AS_PATH `... 64500 64496`)
- The enumeration of the imperfect options available should be enumerated more systematically, so that the reader can make an easy comparison. At present the proposed solutions are scattered in the example description.

Let me know your thoughts on this?

**Comment by ksriram25** [comment]
Ben: Please go ahead. Make the wording changes you feel are necessary. I can look at the diff and comment afterwards.
