### ISSUE TITLE
Recommendations in RTBH section out of scope

### ISSUE THREAD

**Issue by benmaddison** [goldbe/draft-rpki-maxlength#6]
The recommendations for the validation of RTBH routes seem to go beyond the scope of this document.
RFC 6811 makes no provision for distinguishing between "Invalid due to origin AS" and "Invalid due to prefix-length".
This section may even be read as attempting to update RFC 6811.

At the very least, I think this section should acknowledge that the recommended algorithm is not consistent with RFC 6811, and possibly that other options exist (some of which are highly implementation dependent):
- use SLURM to create a seperate VRP set used to validate RTBH routes (if the set of possible prefixes is known)
- ignore ROV status for RTBH routes
- other, more complex patterns that I won't get into ;-)

**Comment by ksriram25** [comment]
We can simply add this text at the end: There is no attempt here to update RFC 6811. What is being said here that an AS that honors the BLACKHOLE Community for a peer, includes in its local policy a simple check that the more specific prefix announcement (with BLACKHOLE Community) is covered by a ROA that includes the peer's AS number. A BGP speaker receiving an announcement tagged with the BLACKHOLE community SHOULD add the NO_ADVERTISE or NO_EXPORT community (as specified in [RFC7999]).
